service: orderService

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  role: ${file(../roleARN.yaml):roles.LabRole}
  environment:
    TABLE_NAME: ${self:service}-${opt:stage, 'dev'}
    USERS_TABLE: Usuarios

functions:
  crearPedido:
    handler: CrearPedido.lambda_handler
    events:
      - http:
          path: /pedido/crear
          method: post
          cors: true

  obtenerPedido:
    handler: ObtenerPedido.lambda_handler
    events:
      - http:
          path: /pedido/{order_id}
          method: get
          cors: true

  actualizarPedido:
    handler: ActualizarPedido.lambda_handler
    events:
      - http:
          path: /pedido/actualizar
          method: put
          cors: true

  eliminarPedido:
    handler: EliminarPedido.lambda_handler
    events:
      - http:
          path: /pedido/eliminar
          method: delete
          cors: true

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: order_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: order_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: user_id-index
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: tenant_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        LocalSecondaryIndexes:
          - IndexName: created_at-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
